Feature repo management dashboard
poloz-lab/wazuh-puppet pull request #4
Opened 2023-07-06 07:55 UTC by le-ya

2023-07-13 09:14 UTC, poloz-lab requested changes

2023-07-13 09:14 UTC, poloz-lab commented on manifests/dashboard.pp
> +      }
Problème d'indentation ?

2023-07-13 09:14 UTC, poloz-lab commented on manifests/dashboard.pp
> +    },
Problème d'indentation ?

2023-07-13 09:14 UTC, poloz-lab commented on manifests/dashboard.pp
> +    require => Package['wazuh-dashboard'],
Pas besoin car dépend d'une ressource qui dépend déjà du package

2023-07-13 09:14 UTC, poloz-lab commented on manifests/dashboard.pp
> +    notify  => Service['wazuh-dashboard'],
Pourquoi est-ce que toute la ressource est ajoutée alors que le titre du commit indique que ça fix seulement la dépendance ?

2023-07-19 09:23 UTC, poloz-lab requested changes

2023-07-19 09:23 UTC, poloz-lab commented on manifests/dashboard.pp
> +<<<<<<< HEAD
Il y a un conflit

2023-07-20 13:28 UTC, closed without merging

2023-07-24 14:49 UTC, poloz-lab commented
@le-ya Je ne vois pas de réouverture de cette PR, normal ?

2023-07-24 14:53 UTC, le-ya commented
Oui le code du premier commit a été merge, et le deuxième commit n'a plus d'intérêt