Feature wazuh template filebeat
poloz-lab/wazuh-puppet pull request #5
Opened 2023-07-06 08:01 UTC by le-ya

2023-07-06 13:03 UTC, poloz-lab requested changes
Le premier commit est vide

2023-07-06 13:03 UTC, poloz-lab commented on files/wazuh_template_4.3.json
À mettre à jour avec la version 4.4 (nom du fichier + potentiellement contenu ?)

2023-07-06 13:03 UTC, poloz-lab commented on manifests/filebeat_oss.pp
> +    source  => "puppet:///modules/${module_name}/wazuh_template_4.3.json",
Nom à adapter avec la 4.4

2023-07-10 09:16 UTC, le-ya commented
UP

2023-07-13 09:21 UTC, poloz-lab requested changes
Ce serait mieux si la CI trouvait le fichier

2023-07-25 11:33 UTC, poloz-lab commented
Je ne vois pas ce commit dans notre branche 4.3. Je crois qu'on avait décidé de ne pas utiliser cette fonctionnalité.

2023-08-01 13:32 UTC, closed without merging