Feature update filebeat module
poloz-lab/wazuh-puppet pull request #7
Opened 2023-07-12 13:42 UTC by le-ya

2023-07-13 09:32 UTC, poloz-lab requested changes

2023-07-13 09:32 UTC, poloz-lab commented on manifests/filebeat_oss.pp
> +  -> archive { "/tmp/${wazuh_filebeat_module}":
Là le commit fait plus que corriger la typo, j'ai l'impression que ça va dans le commit d'après

2023-07-13 09:32 UTC, poloz-lab commented on manifests/filebeat_oss.pp
> +  -> archive { "/tmp/${$wazuh_filebeat_module}":
Attention, la typo est réintroduite

2023-07-24 14:38 UTC, poloz-lab requested changes

2023-07-24 14:38 UTC, poloz-lab commented on manifests/filebeat_oss.pp
> +
Indentation non nécessaire sur une ligne vide

2023-07-24 14:48 UTC, le-ya commented on manifests/filebeat_oss.pp
> +
Done [✅](https://emojipedia.org/check-mark-button)

2023-07-24 14:53 UTC, poloz-lab commented on manifests/filebeat_oss.pp
> +
Je la vois toujours sur le diff :grimacing:

2023-07-24 15:12 UTC, poloz-lab approved these changes

2023-07-25 11:37 UTC, poloz-lab requested changes

2023-07-25 11:37 UTC, poloz-lab commented on manifests/filebeat_oss.pp
> +  $wazuh_filebeat_module_dir = "/opt/filebeat_wazuh_modules/${basename($wazuh_filebeat_module, '.tar.gz')}"
Ajout d'une ligne vide avant pour espacer

2023-07-31 09:05 UTC, poloz-lab approved these changes

2023-07-31 09:05 UTC, merged